apiVersion: v1
kind: Secret
metadata:
  name: fastfood-production-secret
type: Opaque
data:
  ConnectionStrings__SqlServerConnection: 'U2VydmVyPW15ZGIuY3h5NDB3c3lhbmI4LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtEYXRhYmFzZT1GYXN0Rm9vZDtVc2VyIElkPWRidXNlcjtQYXNzd29yZD1kYnBhc3N3b3JkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9dHJ1ZQ=='
  RabbitMQ__HostName: 'Yi03OGExMDIxZi0xNzJjLTQyYjItOGJkNS00NTViNmYxMTE5MTcubXEudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20='
  RabbitMQ__UserName: 'cmFiYml0VXNlcg=='
  RabbitMQ__Password: 'cmFiYml0UGFzc3dvcmQ='
  RabbitMQ__PaymentQueueName: 'UGF5bWVudFF1ZXVl'
  RabbitMQ__ProductionQueueName: 'UHJvZHVjdGlvblF1ZXVl'
  RabbitMQ__OrderQueueName: 'T3JkZXJRdWV1ZQ=='
